version: '3.8'

x-source-os: &source-os linux
x-per-page: &per-page 10
x-source-path: &source-path /Users/apple/Desktop/
x-target-path: &target-path /mnt

services:
  dev:
    container_name: file_listing_dev
    image: file-listing-dev:1.0.0
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      OS: *source-os
      PER_PAGE: *per-page
      SOURCE_ROOT_DIR: *source-path
      TARGET_ROOT_DIR: *target-path
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - type: bind
        source: *source-path
        target: *target-path
    restart: unless-stopped
  prod:
    container_name: file_listing_prod
    image: file-listing-prod:1.0.0
    environment:
      OS: *source-os
      PER_PAGE: *per-page
      SOURCE_ROOT_DIR: *source-path
      TARGET_ROOT_DIR: *target-path
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - /usr/src/app
      - type: bind
        source: *source-path
        target: *target-path
    restart: unless-stopped

networks:
  nesjs-network:
